version: '3'

services:
  emotions-kotlin-server:
    build:
      dockerfile: Dockerfile
      context: .
    image: emotions-kotlin-server
    container_name: 'kotlin-server'
    networks:
      - emotion
    ports:
      - "8080:8080"
    command: ["java","-jar","/app/EmotionsServer.jar"]
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres


  postgres:
    image: postgres:16.3-alpine
    networks:
      - emotion
    environment:
      POSTGRES_DB: "EmotionsForum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

networks:
  emotion:
    driver: bridge