version: '3'

services:
  emotions-kotlin-server:
    build:
      dockerfile: Dockerfile
      context: .
    image: emotions-kotlin-server
    container_name: 'emotions-kotlin-server'
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: "EmotionsForum"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"