spring:
  application:
    name: EmotionsServer
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/EmotionsForum
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
