spring:
  application:
    name: EmotionsServer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://my-teamup.ru:5432/EmotionsForum
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
